from pile import * # "*" = import de toutes les fonctions
s = newstack()
push(s, 11)
push(s, 12)
push(s, 13)
print("le contenu de la pile est : {}".format(s))
sommet = top(s)
print("le sommet de la pile est : {}".format(sommet))
while not isEmpty(s):
   print("---")
   item = pop(s)
   emptyStack = isEmpty(s)
   stackSize = size(s)
   print("l'élement dépilé est : {}".format(item) )
   print("la pile est vide ? : {}".format(emptyStack))
   print("la taille de la pile est : {}".format(stackSize))
